// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Eng6VFcxAHLxQZo1jetwVrcdwnuwONA',
    appId: '1:711018129396:web:dbefbbd20f4ac6e9ee3ba1',
    messagingSenderId: '711018129396',
    projectId: 'sistema-rh-ifba',
    authDomain: 'sistema-rh-ifba.firebaseapp.com',
    storageBucket: 'sistema-rh-ifba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRxfRLptAXViuijibcXd6st-tyYDq1W0',
    appId: '1:711018129396:android:681e284770895930ee3ba1',
    messagingSenderId: '711018129396',
    projectId: 'sistema-rh-ifba',
    storageBucket: 'sistema-rh-ifba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXh8iIAuMX2qAr52IACyFFDxhNUxEFUWE',
    appId: '1:711018129396:ios:ba8ed091def4fa54ee3ba1',
    messagingSenderId: '711018129396',
    projectId: 'sistema-rh-ifba',
    storageBucket: 'sistema-rh-ifba.firebasestorage.app',
    iosBundleId: 'com.example.rhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXh8iIAuMX2qAr52IACyFFDxhNUxEFUWE',
    appId: '1:711018129396:ios:ba8ed091def4fa54ee3ba1',
    messagingSenderId: '711018129396',
    projectId: 'sistema-rh-ifba',
    storageBucket: 'sistema-rh-ifba.firebasestorage.app',
    iosBundleId: 'com.example.rhApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Eng6VFcxAHLxQZo1jetwVrcdwnuwONA',
    appId: '1:711018129396:web:4314676878004769ee3ba1',
    messagingSenderId: '711018129396',
    projectId: 'sistema-rh-ifba',
    authDomain: 'sistema-rh-ifba.firebaseapp.com',
    storageBucket: 'sistema-rh-ifba.firebasestorage.app',
  );
}
