// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FgH5Ngy-M-NeH1cDz5f-G-lKGORbr7I',
    appId: '1:560617958664:web:6fc99baad4256f4c9d50bd',
    messagingSenderId: '560617958664',
    projectId: 'gestor-rh-33471',
    authDomain: 'gestor-rh-33471.firebaseapp.com',
    storageBucket: 'gestor-rh-33471.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uMVAAITOscZFWiQJVPvAp5_ygxbWno8',
    appId: '1:560617958664:android:75471fc8d3c068019d50bd',
    messagingSenderId: '560617958664',
    projectId: 'gestor-rh-33471',
    storageBucket: 'gestor-rh-33471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYr5H1oMhZKK9pcLd5SF3YV3nw_camwCE',
    appId: '1:560617958664:ios:fb070b70df00e97b9d50bd',
    messagingSenderId: '560617958664',
    projectId: 'gestor-rh-33471',
    storageBucket: 'gestor-rh-33471.firebasestorage.app',
    iosBundleId: 'com.example.rhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYr5H1oMhZKK9pcLd5SF3YV3nw_camwCE',
    appId: '1:560617958664:ios:fb070b70df00e97b9d50bd',
    messagingSenderId: '560617958664',
    projectId: 'gestor-rh-33471',
    storageBucket: 'gestor-rh-33471.firebasestorage.app',
    iosBundleId: 'com.example.rhApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_FgH5Ngy-M-NeH1cDz5f-G-lKGORbr7I',
    appId: '1:560617958664:web:a8d309b2c31d40fb9d50bd',
    messagingSenderId: '560617958664',
    projectId: 'gestor-rh-33471',
    authDomain: 'gestor-rh-33471.firebaseapp.com',
    storageBucket: 'gestor-rh-33471.firebasestorage.app',
  );

}